### ISSUE TITLE
GNOME 45. After reboot it got to the upper row

### ISSUE THREAD

**Issue by darkblaze69** [kra-mo/quick-touchpad-toggle#7] opened 2023-08-11 17:31 UTC
GNOME 45. After reboot it got to the upper row.
The error: (intermediate value).statusArea.quickSettings._backgroundApps is undefined

![Screenshot from 2023-08-11 22-29-42](https://github.com/kra-mo/quick-touchpad-toggle/assets/6976920/8b5f6b9a-5858-4958-bb19-16c396780db8)

**Comment by kra-mo** [comment] 2023-08-11 19:30
ughhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by kra-mo** [comment] 2023-08-11 19:34
Which version of 45 are you on?

**Comment by kra-mo** [comment] 2023-08-11 19:34
As in, what distro and package version?

**Comment by darkblaze69** [comment] 2023-08-11 19:42
Arch Linux, based on FCGU repo, mutter and gnome-shell latest main.

**Comment by kra-mo** [comment] 2023-08-11 19:47
Well, that's something, because I cannot reproduce it and I'm also not doing anything out of the ordinary. Might just be a temporary thing. Please reopen if the issue isn't fixed by the time 45 is stable.

**Closed as completed by kra-mo** 2023-08-11 19:47 UTC
